spring.application.name=VacationRequest

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://192.168.2.26:5432/vacation_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
jwt.secret=U2VjdXJlU3VwZXJTZWNyZXRLZXlGb3JWYWNhdGlvblJlcXVlc3QyMDI2IQ==
jwt.expiration=86400000


# ===== Microsoft 365 Graph Mail =====
m365.tenant-id=bb44723c-deda-46f4-b0a4-6fdad6713918
m365.client-id=c8827841-480b-4d13-81e6-759b17602d75
m365.client-secret=${M365_CLIENT_SECRET}
m365.from-email=no-reply@cmsegypt.net

mail.mode=mock
# later: mail.mode=graph


app.jwt.secret=CHANGE_ME_TO_A_VERY_LONG_SECRET_AT_LEAST_64_CHARS_1234567890_CHANGE_ME
app.jwt.access-token-minutes=60
app.jwt.issuer=vacation-request
